### ISSUE TITLE
Usage of Full-System QASan

### ISSUE THREAD

**Issue by crhf** [andreafioraldi/qasan#18]
I compiled `qasan-system` for ARM and ran an ARM system like this:
```
qasan-system -M vexpress-a9 -m 256M -dtb vexpress-v2p-ca9.dtb -nographic -kernel zImage -append "root=/dev/mmcblk0 console=ttyAMA0 rw" -sd a9rootfs.ext3
```
Then I ran the following program inside `qasan-system` (it had been cross-compiled with `arm-linux-gnueabi-gcc` statically and put into `a9rootfs.ext3` beforehand):
```
#include <stdio.h>
#include <stdlib.h>

int main() {
    int *a = (int *)malloc(3 * sizeof(int));
    int b = a[10];  // out of bound
    printf("b = %d\n", b);
    free(a);
    return 0;
}
```
I expected QASan to detect the out-of-bound access and output some information, but it didn't. Is this the right usage of `qasan-system`? I know I can run this program with user-mode QASan but want to experiment with the system mode. Thanks in advance!

**Comment by andreafioraldi** [comment]
it is just for x86 and you need to hook the allocator of the guest to issue the hypercalls that inserts the redzones etc.

**Comment by crhf** [comment]
> it is just for x86 and you need to hook the allocator of the guest to issue the hypercalls that inserts the redzones etc.

What does "just for x86" mean? Doesn't full-system QASan support ARM?

**Comment by andreafioraldi** [comment]
no

**Comment by crhf** [comment]
I got the `qasan-system` by running `./build.py --arch arm --system --cross arm-linux-gnueabi-gcc`. Now that ARM isn't supported, what is this `qasan-system`? Is it just an ordinary QEMU?

**Comment by andreafioraldi** [comment]
No, it is a patched QEMU with shadow memory and hooks that is slower than QEMU and cannot sanitize because I never implemented an hypercall for ARM
