### ISSUE TITLE
How can I build qasan for arm?

### ISSUE THREAD

**Issue by spidermana** [andreafioraldi/qasan#2]
Hi, I encountered some difficulties related to qasan for arm.
I sincerely ask for a help.

If I need to build qasan for arm，what <path_for_dso> to specify?
Command: `./build.py --asan-dso <path_for_dso> --arch arm --cross arm-linux-gnueabi-gcc`

And I didn't find anything concerned with `arm`  under `usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/`.
If I ignore something important?

Additionally, could you please add some examples on how to build qasan for other architectures supported?

**Comment by andreafioraldi** [comment]
Qemu must be built using an arch with the same bits of the target arch, so for arm an i386 version of qemu will be built.
Make sure to have the ia32-libs installed on your x86_64 system.
The ASan Dso is libclang_rt.asan-i386.so, on Ubuntu 18 the path is the above only if you have clang-8 installed. Anyway, it should be easy to find for other clang versions.

**Comment by spidermana** [comment]
Thanks. I have tested aarch64 yet!
With command: `./build.py --arch arm64 --cross aarch64-linux-gnu-gcc --asan-dso /usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.asan-x86_64.so `

Bother you to confirm whether the command above is correct?

So far I've only compiled simple C Code:
```
#include <stdlib.h>
#include <stdio.h>

int main() {

  char * a = malloc(10);

  char * b = malloc(10);

  b[9] = 'a';
  printf("this is a double-free test for arm64\n");
  free(a);

  free(b);

  free(a);

}
```

And this is what qasan returns while executing that file:
```
spiderman@ubuntu:~/Tools/tests/qasan$ file ./qasan-qemu 
./qasan-qemu: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=eefe04e0737d8b52aad1d0662c36ea859cfb633d, with debug_info, not stripped
spiderman@ubuntu:~/Tools/tests/qasan$ aarch64-linux-gnu-gcc -L /usr/aarch64-linux-gnu/ ./tests/double_free.c -o ./tests/double_free_for_arm64
spiderman@ubuntu:~/Tools/tests/qasan$ file ./tests/double_free_for_arm64 
./tests/double_free_for_arm64: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, BuildID[sha1]=f8da406a73d769606fa95a562e10ecba5920c549, not stripped
spiderman@ubuntu:~/Tools/tests/qasan$ ./qasan-qemu -L /usr/aarch64-linux-gnu ./tests/double_free_for_arm64
this is a double-free test for arm64
spiderman@ubuntu:~/Tools/tests/qasan$ 
```

Why it didn't throw an exception? 
Is there something wrong?

**Comment by andreafioraldi** [comment]
Yes, you have to use `qasan` not `qasan-qemu`, like the example in the readme. `qasan` is a wrapper to `qasan-qemu` that preloads the runtime, so you can also use `./qasan-qemu -E LD_PRELOAD=./libqasan.so ./binary`

**Comment by andreafioraldi** [comment]
Reagrds the ARM root, use the QEMU env var, `QEMU_LD_PREFIX=/usr/aarch64-linux-gnu`.
So the command is:

```
export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
./qasan ./tests/double_free_for_arm64
```

**Comment by andreafioraldi** [comment]
Let me know if there is something wrong, I'm extending QASan to fullsystem x86 in this week and I didn't tested yet for regressions in the ARM/ARM64 code.

**Comment by spidermana** [comment]
Ok, I get it now, thanks!
