### ISSUE TITLE
Installation and usage problems for the 32-bit architectures

### ISSUE THREAD

**Issue by buptsseGJ** [andreafioraldi/qasan#7]
Hi, I found it an interesting job and tried to use it. But I met with some confusion. So, I have two questions for help.

1. I built qasan for the 32-bit x86 architecture. As the readme mentioned, i386 libraries need to be installed and PKG_CONFIG_PATH needs to be set. Then I installed the i386 libraries in some manners similar to ` apt-get install lib32ncurses5 ​lib32z1` or `apt-get install g++-multilib libncurses5:i386 libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i38`.
Unfortunately, I can not find the `/usr/lib/i386-linux-gnu/pkgconfig` in my filesystem with Ubuntu 18.04.3. So, the error is as follows:
```
sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.        
You probably need to set PKG_CONFIG_LIBDIR       
to point to the right pkg-config files for your build target
```
**I also tried online solutions, but it didn't work. I'd like to know how you solved the problem.**

2. After reading the build.py code, I understood that the asan-giovese mode implemented by yourself only supported x86 (_64), not arm, etc. Is my understanding correct？
Thank you very much. Looking forward to your reply.

**Comment by buptsseGJ** [comment]
After installing the *-dev packages through commands "apt-get install *-dev:i386", the  `/usr/lib/i386-linux-gnu/pkgconfig` appeared, only several .pc files were here:
```
$ ls /usr/lib/i386-linux-gnu/pkgconfig/
form.pc  menu.pc  ncurses.pc  ncurses++.pc  panel.pc  tic.pc  tinfo.pc
```
Then I set up the PKG_CONFIG_PATH env variable `export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig`. But it didn't work，the same error occurred. 
```
$ ./build.py --arch x86 --cc clang-8 --cxx clang++-8 --asan-dso /usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.asan-i386.so

sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.        
You probably need to set PKG_CONFIG_LIBDIR       
to point to the right pkg-config files for your build target
```

I doubted I was missing some packages, so I used the command `apt build-dep qemu && apt install libglib2.0:i386 libglib2.0-dev:i386`. Some new .pc files can be seen. 
```
$ ls /usr/lib/i386-linux-gnu/pkgconfig/
form.pc          glib-2.0.pc            gmodule-no-export-2.0.pc  libpcre16.pc   libpcre.pc       ncurses.pc    tic.pc
gio-2.0.pc       gmodule-2.0.pc         gobject-2.0.pc            libpcre32.pc   libpcreposix.pc  ncurses++.pc  tinfo.pc
gio-unix-2.0.pc  gmodule-export-2.0.pc  gthread-2.0.pc            libpcrecpp.pc  menu.pc          panel.pc      zlib.pc
```
The same error occurred again. I don't know where is wrong. Thanks.

**Comment by andreafioraldi** [comment]
Hi @buptsseGJ , this is strange, if you can compile QEMU setting PKG_CONFIG_PATH you can compile QASan. Btw, if you avoid to specify asan-dso and use my own asan implementation, you can build qemu for x64 and emulate i386 without the need to build also qemu for i386.

**Comment by andreafioraldi** [comment]
It is not completely thread safe and now I don't have free time to work on it, but I will complete it one day.

**Comment by buptsseGJ** [comment]
The original QEMU 3.1.1 with `--target-list=i386-linux-user,arm-linux-user` cannot be compiled in my environment. Maybe glib or something else has gone wrong, and I'll try again later.
Thank for your reply.

**Comment by andreafioraldi** [comment]
I close this issue cause this is a problem of your setup with qemu
